Repository gardener/machine-controller-manager-provider-vsphere, pull requests merged in 2020-07, with the labels that each got.

#2 fix for cloudinit addSSHKeys method
  pkg/vsphere/internal/vapp_helper.go
  pkg/vsphere/internal/vapp_helper_test.go
Labels: reviewed/ok-to-test

#3 dealing with cloudinit shell scripts
  VERSION
  pkg/vsphere/internal/clone.go
  pkg/vsphere/internal/vapp_helper.go
Labels: needs/ok-to-test

#4 Use channel id for posting slack release notes
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm
